# Generated by Django 4.2.4 on 2023-09-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-dt_publicado"]},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_bb7600_idx",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="corpo",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated",
            new_name="dt_atualizado",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created",
            new_name="dt_criado",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="publish",
            new_name="dt_publicado",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="titulo",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-dt_publicado"], name="blog_post_dt_publ_4ad93b_idx"
            ),
        ),
    ]
